---
driver:
  name: vagrant

platforms:
- name: ubuntu-16.04
- name: ubuntu-18.04
- name: centos-6
- name: centos-7
- name: centos-8
- name: oracle-6
- name: oracle-7
- name: debian-8
- name: debian-9
- name: debian-10
- name: fedora-29
- name: fedora-30
- name: opensuse-leap-42
- name: amazonlinux-1
  driver_config:
    box: realreadme/amazon2016.09
- name: amazonlinux-2
  driver_config:
    box: stakahashi/amazonlinux2

provisioner:
  name: chef_solo
<% if ENV['CHEF_VERSION'] %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'] %>
<% end %>
  chef_license: accept

verifier:
  name: inspec
  chef_license: accept

suites:
- name: default
  run_list:
  - recipe[test]
  - recipe[ssh-hardening]
- name: rhel-with-disabled-pam
  includes:
    - centos-6
    - centos-7
    - centos-8
    - fedora-29
    - fedora-30
    - oracle-6
    - oracle-7
  driver:
    provision: true
    vagrantfiles:
      - test/fixtures/vagrantfiles/enforce_selinux.rb
  run_list:
  - recipe[test]
  - recipe[ssh-hardening]
  attributes:
    ssh-hardening:
      ssh:
        server:
          use_pam: false
  verifier:
    inspec_tests:
      - test/integration/default
      - test/integration/without-pam
