---
AllCops:
  DisplayCopNames: true
  Exclude:
  - vendor/**/*
  - test/**/*
  TargetRubyVersion: 2.4
Metrics/AbcSize:
  Max: 29
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Max: 40
Metrics/PerceivedComplexity:
  Max: 10
Style/Documentation:
  Enabled: false
Layout/DotPosition:
  EnforcedStyle: trailing
  Enabled: true
Style/Encoding:
  EnforcedStyle: always
  Enabled: true
Layout/ExtraSpacing:
  Exclude:
    - attributes/default.rb
Style/RegexpLiteral:
  AllowInnerSlashes: true
Layout/SpaceAroundOperators:
  Exclude:
    - attributes/default.rb
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
